name:           My Radio
description:    Stream music from your computer to Echo
nickname:       My Radio
plugin_version: 2.2.0
#baseurl:        https://alexa.blackdata.ca
highlight:      true
future:         false #do not show post-dated posts
markdown:       kramdown
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
collections:
  examples:
    output: true
exclude:
  - node_modules/
twitter_username: blackdata7
title_image: images/ach_blue_small_32x32.png
